version: "3"
services:
  postgres:
    image: "postgres:11"
    hostname: "moto-db"
    container_name: "moto-db"
    environment:
      - PGDATA=/pg
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=motorent
    ports:
      - "5432:5432"
    volumes:
      - dev_test:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dev_test: